import 'assets/fonts/Raleway/Raleway-Black.ttf'
import 'assets/fonts/Raleway/Raleway-BlackItalic.ttf'
import 'assets/fonts/Raleway/Raleway-Bold.ttf'
import 'assets/fonts/Raleway/Raleway-BoldItalic.ttf'
import 'assets/fonts/Raleway/Raleway-ExtraBold.ttf'
import 'assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf'
import 'assets/fonts/Raleway/Raleway-ExtraLight.ttf'
import 'assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf'
import 'assets/fonts/Raleway/Raleway-Italic.ttf'
import 'assets/fonts/Raleway/Raleway-Light.ttf'
import 'assets/fonts/Raleway/Raleway-LightItalic.ttf'
import 'assets/fonts/Raleway/Raleway-Medium.ttf'
import 'assets/fonts/Raleway/Raleway-MediumItalic.ttf'
import 'assets/fonts/Raleway/Raleway-Regular.ttf'
import 'assets/fonts/Raleway/Raleway-SemiBold.ttf'
import 'assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf'
import 'assets/fonts/Raleway/Raleway-Thin.ttf'
import 'assets/fonts/Raleway/Raleway-ThinItalic.ttf'

// export const style = { black }